name: Testing Build Steps

on: push

jobs:
  build:
    name: Ody base
    runs-on: windows-latest
    steps:
      - name: Environment-Setup
        shell: pwsh
        run: choco install nuget.commandline -y


